import { useMemo, useState } from 'react'
import { AlertTriangle, BusFront, CalendarDays, CheckCircle2, Clock3, Eye, MapPin, Plus, Route, Truck, Wrench } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import { DataTable, EmptyState, Modal, PageHeader, StatCard, StatusBadge, Toast } from '../components/common/UI'
import { ConfirmDialog, DetailList, DocumentCenter, ExportButton, Field, FilterBar, Pagination, ProgressBar, SearchInput, usePagination } from '../components/common/OperationsUI'
import { logisticsMenu } from '../data/content'
import { useAppData } from '../hooks/useAppData'
import { batchStatusLabels, formatDateTime, getBatchTone } from '../utils/batchUtils'

const pickupGroups={ready:['scheduled','armada_assigned'],progress:['en_route','arrived','issue'],done:['completed'],attention:['cancelled']}
function pickupTone(status){if(status==='completed')return'success';if(['en_route','arrived'].includes(status))return'info';if(status==='issue')return'error';if(status==='cancelled')return'neutral';return'warning'}
function pickupLabel(status){return {scheduled:'Siap dijemput',armada_assigned:'Armada ditugaskan',en_route:'Dalam perjalanan',arrived:'Tiba',issue:'Kendala',completed:'Selesai',cancelled:'Dibatalkan'}[status]||status}

export function LogisticsPickupPage(){
  const nav=useNavigate(); const {state,assignPickup,startRoute,markArrived,beginQuality,completePickup,markPickupIssue,cancelPickup}=useAppData()
  const [tab,setTab]=useState('ready');const[query,setQuery]=useState('');const[urgency,setUrgency]=useState('Semua');const[selected,setSelected]=useState(null);const[action,setAction]=useState(null);const[reason,setReason]=useState('');const[toast,setToast]=useState('')
  const route=state.logisticsRoutes[0]
  const rows=state.pickupSchedules.map((schedule)=>{const batch=state.batches.find((item)=>item.batchId===schedule.batchId);const stop=route.stops.find((item)=>item.batchId===schedule.batchId);return{...schedule,batch,stop,urgency:stop?.urgency||'Sedang'}}).filter((item)=>item.batch&&pickupGroups[tab].includes(item.status)&&(!query||`${item.batchId} ${item.batch.sppgName}`.toLowerCase().includes(query.toLowerCase()))&&(urgency==='Semua'||item.urgency===urgency))
  const active=route.stops[route.currentStopIndex]
  const perform=(name,item)=>{setSelected(item);setAction(name);setReason('')}
  const confirm=()=>{if(action==='issue')markPickupIssue(selected.batchId,reason||'Kendala operasional');if(action==='cancel')cancelPickup(selected.batchId,reason||'Dibatalkan oleh mitra logistik');setAction(null);setSelected(null);setToast(action==='issue'?'Kendala disimpan dan terlihat pada monitoring.':'Penjemputan dibatalkan dengan alasan tercatat.')}
  return <DashboardLayout menu={logisticsMenu} contextLabel="Borneo Circular Logistik"><PageHeader title="Manajemen Penjemputan" description="Kelola penugasan armada, kedatangan, pemeriksaan mutu, pemuatan, kendala, dan penyelesaian titik dari satu workspace."/>
    <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{[['ready','Siap Dijemput'],['progress','Dalam Proses'],['done','Selesai'],['attention','Tindak Lanjut']].map(([key,label])=><button key={key} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold transition ${tab===key?'bg-brand-500 text-white shadow-lg':'border border-border bg-white text-muted hover:bg-soft'}`} onClick={()=>setTab(key)}>{label}<span className="ml-2 rounded-full bg-white/20 px-2 py-0.5 text-xs">{state.pickupSchedules.filter((item)=>pickupGroups[key].includes(item.status)).length}</span></button>)}</div>
    <FilterBar><div className="flex-1"><SearchInput value={query} onChange={setQuery} placeholder="Cari Batch ID atau nama SPPG"/></div><select className="input-field md:w-48" value={urgency} onChange={(e)=>setUrgency(e.target.value)}><option>Semua</option><option>Tinggi</option><option>Sedang</option><option>Rendah</option></select></FilterBar>
    {rows.length?<div className="grid gap-4 xl:grid-cols-2">{rows.map((item)=><article key={item.id} className="premium-card border border-border bg-white p-5 shadow-soft"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.12em] text-brand-700">{item.batchId}</div><h2 className="mt-2 font-bold text-ink">{item.batch.sppgName}</h2><div className="mt-1 flex items-center gap-2 text-xs text-muted"><MapPin size={14}/>{item.batch.location}</div></div><StatusBadge tone={pickupTone(item.status)}>{pickupLabel(item.status)}</StatusBadge></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{[['Volume',`${item.batch.volume} L`],['Urgensi',item.urgency],['Kendaraan',item.vehicle],['Jadwal',formatDateTime(item.scheduledAt)]].map(([label,value])=><div key={label} className="rounded-xl bg-soft p-3"><div className="text-xs text-muted">{label}</div><div className="mt-1 font-semibold text-ink">{value}</div></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><button className="btn-secondary !px-3 !py-2 text-xs" onClick={()=>setSelected(item)}><Eye size={15}/> Detail</button>{['scheduled','armada_assigned'].includes(item.status)&&<button className="btn-primary !px-3 !py-2 text-xs" onClick={()=>{const vehicle=state.fleet.find((x)=>x.status==='available')||state.fleet[0];assignPickup({batchId:item.batchId,vehicle:vehicle.plate,driver:vehicle.driver});setToast('Armada dan petugas berhasil ditugaskan.')}}><Truck size={15}/> Assign Armada</button>}{active?.batchId===item.batchId&&route.journeyStatus==='ready'&&<button className="btn-primary !px-3 !py-2 text-xs" onClick={startRoute}>Mulai Penjemputan</button>}{active?.batchId===item.batchId&&['started','next_stop'].includes(route.journeyStatus)&&<button className="btn-primary !px-3 !py-2 text-xs" onClick={markArrived}>Tandai Tiba</button>}{active?.batchId===item.batchId&&route.journeyStatus==='arrived'&&<button className="btn-primary !px-3 !py-2 text-xs" onClick={()=>{beginQuality(item.batchId);nav(`/logistik/verifikasi?batch=${item.batchId}&from=pickup`)}}>Verifikasi Mutu</button>}{active?.batchId===item.batchId&&item.stop?.status==='verified'&&<button className="btn-primary !px-3 !py-2 text-xs" onClick={completePickup}>Selesaikan Pemuatan</button>}{!['completed','cancelled'].includes(item.status)&&<button className="btn-secondary !px-3 !py-2 text-xs" onClick={()=>perform('issue',item)}><AlertTriangle size={15}/> Kendala</button>}{!['completed','cancelled'].includes(item.status)&&<button className="rounded-xl border border-red-200 px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50" onClick={()=>perform('cancel',item)}>Batalkan</button>}</div></article>)}</div>:<EmptyState title="Tidak ada penjemputan pada status ini" description="Item akan berpindah otomatis ketika status rute, pemeriksaan mutu, atau pemuatan berubah."/>}
    <Modal open={Boolean(selected)&&!action} onClose={()=>setSelected(null)} title={`Detail ${selected?.batchId||''}`}>{selected&&<DetailList items={[["SPPG",selected.batch.sppgName],["Lokasi",selected.batch.location],["Volume",`${selected.batch.volume} liter`],["Kapasitas wadah",`${selected.batch.containerCapacity} liter`],["Urgensi",selected.urgency],["Kendaraan",selected.vehicle],["Petugas",selected.driver||'Belum ditugaskan'],["Status mutu",selected.batch.qualityGrade||'Belum diverifikasi'],["Status perjalanan",pickupLabel(selected.status)],["Pembaruan",formatDateTime(selected.batch.updatedAt)]]}/>}</Modal>
    <Modal open={Boolean(action)} onClose={()=>setAction(null)} title={action==='issue'?'Catat Kendala Penjemputan':'Batalkan Penjemputan'} size="max-w-lg"><Field label="Alasan"><textarea className="input-field min-h-28" value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Tuliskan alasan yang dapat ditindaklanjuti."/></Field><div className="mt-5 flex justify-end gap-3"><button className="btn-secondary" onClick={()=>setAction(null)}>Batal</button><button className={action==='cancel'?'rounded-xl bg-red-600 px-5 py-3 font-semibold text-white':'btn-primary'} onClick={confirm}>Simpan</button></div></Modal><Toast message={toast} onClose={()=>setToast('')}/>
  </DashboardLayout>
}

export function FleetManagementPage(){
  const {state,upsertFleet,setFleetStatus}=useAppData();const[query,setQuery]=useState('');const[selected,setSelected]=useState(null);const[editing,setEditing]=useState(null);const[toast,setToast]=useState('')
  const vehicles=state.fleet.filter((item)=>!query||`${item.plate} ${item.driver} ${item.type}`.toLowerCase().includes(query.toLowerCase()))
  const save=(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);const item={id:editing?.id||`VEH-${Date.now()}`,plate:data.get('plate'),type:data.get('type'),capacity:Number(data.get('capacity')),currentLoad:Number(editing?.currentLoad||0),driver:data.get('driver'),status:data.get('status'),lastLocation:data.get('lastLocation'),activeRoute:editing?.activeRoute||null,batches:editing?.batches||[],inspectionDate:data.get('inspectionDate'),roadworthy:data.get('roadworthy'),notes:data.get('notes')};upsertFleet(item);setEditing(null);setToast('Data armada berhasil disimpan.')}
  return <DashboardLayout menu={logisticsMenu} contextLabel="Borneo Circular Logistik"><PageHeader title="Manajemen Armada" description="Pantau kapasitas, sopir, kelayakan, penugasan, muatan, dan status operasional kendaraan." action={<button className="btn-primary" onClick={()=>setEditing({})}><Plus size={17}/> Tambah Armada</button>}/><FilterBar><div className="flex-1"><SearchInput value={query} onChange={setQuery} placeholder="Cari kendaraan atau sopir"/></div></FilterBar><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{vehicles.map((item)=>{const percent=item.capacity?Math.round(item.currentLoad/item.capacity*100):0;return <article key={item.id} className="premium-card border border-border bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-100 text-brand-700"><BusFront/></div><StatusBadge tone={item.status==='available'?'success':item.status==='maintenance'?'warning':item.status==='inactive'?'error':'info'}>{item.status}</StatusBadge></div><h2 className="mt-4 text-lg font-bold text-ink">{item.plate}</h2><p className="text-sm text-muted">{item.type} · {item.driver}</p><div className="mt-5"><ProgressBar value={percent} label={`${item.currentLoad} dari ${item.capacity} liter`} tone={percent>=90?'error':percent>=75?'warning':'brand'}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-soft p-3"><span className="text-muted">Lokasi terakhir</span><strong className="mt-1 block text-ink">{item.lastLocation}</strong></div><div className="rounded-xl bg-soft p-3"><span className="text-muted">Kelayakan</span><strong className="mt-1 block text-ink">{item.roadworthy}</strong></div></div><div className="mt-5 flex gap-2"><button className="btn-secondary flex-1 !py-2 text-xs" onClick={()=>setSelected(item)}>Detail</button><button className="btn-secondary flex-1 !py-2 text-xs" onClick={()=>setEditing(item)}>Edit</button>{item.status==='maintenance'?<button className="btn-primary flex-1 !py-2 text-xs" onClick={()=>setFleetStatus(item.id,'available','Pemeliharaan selesai')}>Aktifkan</button>:<button className="btn-secondary flex-1 !py-2 text-xs" onClick={()=>setFleetStatus(item.id,'maintenance','Pemeriksaan terjadwal')}><Wrench size={14}/> Servis</button>}</div></article>})}</div>
  <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={`Detail Armada ${selected?.plate||''}`}>{selected&&<><DetailList items={[["Vehicle ID",selected.id],["Nomor polisi",selected.plate],["Jenis",selected.type],["Sopir",selected.driver],["Kapasitas",`${selected.capacity} liter`],["Muatan",`${selected.currentLoad} liter`],["Rute aktif",selected.activeRoute||'Tidak ada'],["Batch dibawa",selected.batches?.join(', ')||'Tidak ada'],["Tanggal pemeriksaan",selected.inspectionDate],["Catatan",selected.notes]]}/><div className="mt-5"><h3 className="font-bold text-ink">Aktivitas kendaraan</h3><div className="mt-3 space-y-3">{state.activities.filter((activity)=>activity.detail.includes(selected.plate)).slice(0,5).map((activity)=><div key={activity.id} className="rounded-xl border border-border p-3"><div className="text-sm font-semibold text-ink">{activity.title}</div><div className="mt-1 text-xs text-muted">{formatDateTime(activity.timestamp)}</div></div>)}</div></div></>}</Modal>
  <Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title={editing?.id?'Edit Armada':'Tambah Armada'}><form onSubmit={save} className="grid gap-4 md:grid-cols-2">{[['plate','Nomor polisi'],['type','Jenis kendaraan'],['capacity','Kapasitas maksimum','number'],['driver','Sopir'],['lastLocation','Lokasi terakhir'],['inspectionDate','Tanggal pemeriksaan','date'],['roadworthy','Status kelayakan'],['notes','Catatan']].map(([name,label,type='text'])=><Field key={name} label={label}><input required type={type} name={name} defaultValue={editing?.[name]||''} className="input-field"/></Field>)}<Field label="Status"><select name="status" defaultValue={editing?.status||'available'} className="input-field"><option value="available">Tersedia</option><option value="assigned">Ditugaskan</option><option value="in_transit">Dalam perjalanan</option><option value="full">Penuh</option><option value="maintenance">Pemeliharaan</option><option value="inactive">Tidak aktif</option></select></Field><div className="md:col-span-2 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Batal</button><button className="btn-primary">Simpan Armada</button></div></form></Modal><Toast message={toast} onClose={()=>setToast('')}/></DashboardLayout>
}

export function LogisticsHistoryPage(){
  const {state}=useAppData();const[query,setQuery]=useState('');const[vehicle,setVehicle]=useState('Semua');const[status,setStatus]=useState('Semua');const[selected,setSelected]=useState(null)
  const rows=useMemo(()=>state.pickupSchedules.map((pickup)=>{const batch=state.batches.find((item)=>item.batchId===pickup.batchId);const stop=state.logisticsRoutes.flatMap((route)=>route.stops.map((item)=>({...item,routeId:route.id}))).find((item)=>item.batchId===pickup.batchId);return{id:pickup.id,routeId:stop?.routeId||'Belum masuk rute',batchId:pickup.batchId,date:pickup.scheduledAt,sppg:batch?.sppgName||'—',vehicle:pickup.vehicle,driver:pickup.driver||'Belum ditugaskan',volume:batch?.volume||0,distance:stop?.distance||0,duration:stop?Math.round(stop.distance/30*60+12):0,grade:batch?.qualityGrade||'Belum diverifikasi',status:pickup.status,issue:pickup.issueReason||pickup.cancelReason||'—'}}).filter((item)=>(!query||`${item.batchId} ${item.sppg}`.toLowerCase().includes(query.toLowerCase()))&&(vehicle==='Semua'||item.vehicle===vehicle)&&(status==='Semua'||item.status===status)),[state,query,vehicle,status])
  const {page,setPage,totalPages,paged}=usePagination(rows,7)
  const columns=[{key:'routeId',label:'Route ID'},{key:'batchId',label:'Batch ID',render:(v)=><span className="font-semibold text-ink">{v}</span>},{key:'date',label:'Tanggal',render:formatDateTime},{key:'sppg',label:'SPPG'},{key:'vehicle',label:'Kendaraan'},{key:'volume',label:'Volume',render:(v)=>`${v} L`},{key:'distance',label:'Jarak',render:(v)=>`${v} km`},{key:'grade',label:'Grade'},{key:'status',label:'Status',render:(v)=><StatusBadge tone={pickupTone(v)}>{pickupLabel(v)}</StatusBadge>}]
  const completed=rows.filter((item)=>item.status==='completed').length
  return <DashboardLayout menu={logisticsMenu} contextLabel="Borneo Circular Logistik"><PageHeader title="Riwayat Logistik" description="Rekam perjalanan, volume, durasi, mutu, penyelesaian, dan kendala yang berasal dari aktivitas operasional." action={<ExportButton filename="riwayat-logistik.csv" rows={rows}>Export Riwayat</ExportButton>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={Route} label="Total perjalanan" value={String(rows.length)}/><StatCard icon={Truck} label="Volume ditangani" value={`${rows.reduce((s,x)=>s+x.volume,0)} L`}/><StatCard icon={MapPin} label="Jarak simulasi" value={`${rows.reduce((s,x)=>s+x.distance,0).toFixed(1)} km`}/><StatCard icon={CheckCircle2} label="Completion rate" value={`${rows.length?Math.round(completed/rows.length*100):0}%`}/></div><div className="mt-6"><FilterBar><div className="flex-1"><SearchInput value={query} onChange={setQuery}/></div><select className="input-field md:w-48" value={vehicle} onChange={(e)=>setVehicle(e.target.value)}><option>Semua</option>{[...new Set(state.pickupSchedules.map((item)=>item.vehicle))].map((item)=><option key={item}>{item}</option>)}</select><select className="input-field md:w-48" value={status} onChange={(e)=>setStatus(e.target.value)}><option>Semua</option>{[...new Set(state.pickupSchedules.map((item)=>item.status))].map((item)=><option key={item}>{item}</option>)}</select></FilterBar><DataTable columns={columns} rows={paged} onRowClick={setSelected}/><Pagination page={page} totalPages={totalPages} onChange={setPage}/></div><Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={`Perjalanan ${selected?.batchId||''}`}>{selected&&<><DetailList items={[["Route ID",selected.routeId],["SPPG",selected.sppg],["Kendaraan",selected.vehicle],["Petugas",selected.driver],["Volume",`${selected.volume} liter`],["Jarak",`${selected.distance} km`],["Durasi",`${selected.duration} menit`],["Grade",selected.grade],["Status",pickupLabel(selected.status)],["Kendala",selected.issue]]}/><h3 className="mt-6 font-bold text-ink">Timeline perjalanan</h3><div className="mt-3 space-y-3">{state.traceabilityEvents.filter((item)=>item.batchId===selected.batchId).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)).map((item)=><div key={item.id} className="border-l-4 border-brand-400 bg-brand-50 p-4"><div className="text-sm font-semibold text-ink">{item.label}</div><div className="mt-1 text-xs text-muted">{item.description} · {formatDateTime(item.timestamp)}</div></div>)}</div></>}</Modal></DashboardLayout>
}

export function LogisticsDocumentsPage(){const{state}=useAppData();const ids=new Set(state.batches.filter((item)=>item.logisticsPartner).map((item)=>item.batchId));const documents=state.documents.filter((item)=>ids.has(item.batchId)&&['logistics','all'].includes(item.ownerRole));return <DashboardLayout menu={logisticsMenu} contextLabel="Borneo Circular Logistik"><PageHeader title="Dokumen Logistik" description="Manifest, berita acara penjemputan, hasil mutu, route summary, dan chain-of-custody record yang mengikuti progres batch."/><div className="mt-6"><DocumentCenter documents={documents} batches={state.batches} events={state.traceabilityEvents} title="Arsip Operasional Logistik"/></div></DashboardLayout>}
