import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, Download, FileText, Filter, LoaderCircle, Search, ShieldAlert } from 'lucide-react'
import { Modal } from './UI'
import { documentText, downloadText, exportCsv } from '../../utils/exportUtils'
import { formatDateTime } from '../../utils/batchUtils'

export function SearchInput({ value, onChange, placeholder='Cari data...' }) {
  return <label className="relative block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={17}/><span className="sr-only">Pencarian</span><input value={value} onChange={(event)=>onChange(event.target.value)} placeholder={placeholder} className="input-field pl-10"/></label>
}
export function FilterBar({ children }) { return <div className="mb-5 grid gap-3 rounded-2xl border border-border bg-white p-4 shadow-soft md:flex md:items-end"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-muted md:mr-1"><Filter size={15}/> Filter</div>{children}</div> }
export function Field({ label, children, hint, error }) { return <label className="block"><span className="label">{label}</span>{children}{hint&&<span className="mt-1 block text-xs text-muted">{hint}</span>}{error&&<span className="mt-1 block text-xs font-medium text-red-600">{error}</span>}</label> }
export function ProgressBar({ value, label, tone='brand' }) { const color=tone==='warning'?'bg-amber-500':tone==='error'?'bg-red-500':'bg-brand-500'; return <div><div className="mb-1.5 flex justify-between text-xs text-muted"><span>{label}</span><strong>{Math.max(0,Math.min(100,Math.round(value)))}%</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full transition-all duration-700 ${color}`} style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div> }
export function LoadingState({ label='Memproses data...' }) { return <div className="grid min-h-56 place-items-center border border-border bg-white"><div className="text-center text-sm text-muted"><LoaderCircle className="mx-auto mb-3 animate-spin text-brand-600"/><div>{label}</div></div></div> }
export function ErrorState({ title='Data tidak dapat diproses', description }) { return <div className="grid min-h-56 place-items-center border border-red-200 bg-red-50 p-6 text-center"><div><ShieldAlert className="mx-auto text-red-600"/><h3 className="mt-3 font-bold text-red-800">{title}</h3><p className="mt-2 text-sm text-red-700">{description}</p></div></div> }
export function Pagination({ page, totalPages, onChange }) { if(totalPages<=1)return null; return <div className="mt-5 flex items-center justify-end gap-2"><button className="btn-secondary !px-3 !py-2" onClick={()=>onChange(Math.max(1,page-1))} disabled={page===1}><ChevronLeft size={16}/></button><span className="text-sm text-muted">Halaman {page} dari {totalPages}</span><button className="btn-secondary !px-3 !py-2" onClick={()=>onChange(Math.min(totalPages,page+1))} disabled={page===totalPages}><ChevronRight size={16}/></button></div> }
export function usePagination(rows, pageSize=8) { const [page,setPage]=useState(1); const totalPages=Math.max(1,Math.ceil(rows.length/pageSize)); const safePage=Math.min(page,totalPages); const paged=useMemo(()=>rows.slice((safePage-1)*pageSize,safePage*pageSize),[rows,safePage,pageSize]); return {page:safePage,setPage,totalPages,paged} }
export function ConfirmDialog({ open, onClose, onConfirm, title='Konfirmasi tindakan', description, confirmLabel='Lanjutkan', danger=false }) { return <Modal open={open} onClose={onClose} title={title} size="max-w-lg"><p className="text-sm leading-6 text-muted">{description}</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={onClose}>Batal</button><button className={danger?'rounded-xl bg-red-600 px-5 py-3 font-semibold text-white hover:bg-red-700':'btn-primary'} onClick={onConfirm}>{confirmLabel}</button></div></Modal> }
export function DetailList({ items }) { return <dl className="grid gap-3 sm:grid-cols-2">{items.map(([label,value])=><div key={label} className="rounded-xl border border-border bg-soft p-4"><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 break-words text-sm font-semibold text-ink">{value??'—'}</dd></div>)}</dl> }
export function ExportButton({ filename, rows, children='Export CSV' }) { return <button className="btn-secondary !py-2" onClick={()=>exportCsv(filename,rows)} disabled={!rows.length}><Download size={16}/>{children}</button> }
export function DocumentCenter({ documents, batches, events, title='Pusat Dokumen' }) {
  const [query,setQuery]=useState(''); const [type,setType]=useState('Semua'); const [status,setStatus]=useState('Semua'); const [selected,setSelected]=useState(null)
  const types=[...new Set(documents.map((item)=>item.type))]
  const filtered=documents.filter((item)=>(!query||`${item.id} ${item.batchId} ${item.title}`.toLowerCase().includes(query.toLowerCase()))&&(type==='Semua'||item.type===type)&&(status==='Semua'||item.status===status)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))
  const download=(doc)=>{const batch=batches.find((item)=>item.batchId===doc.batchId); downloadText(`${doc.id}.txt`,documentText(doc,batch,events.filter((item)=>item.batchId===doc.batchId)))}
  return <>
    <div className="mb-4 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h2 className="font-bold text-ink">{title}</h2><p className="mt-1 text-xs text-muted">Dokumen terbentuk mengikuti progres batch.</p></div><span className="rounded-full bg-brand-100 px-3 py-1 text-xs font-semibold text-brand-700">{filtered.length} dokumen</span></div>
    <FilterBar><div className="min-w-0 flex-1"><SearchInput value={query} onChange={setQuery} placeholder="Cari Document ID atau Batch ID"/></div><select className="input-field md:w-56" value={type} onChange={(e)=>setType(e.target.value)}><option>Semua</option>{types.map((item)=><option key={item}>{item}</option>)}</select><select className="input-field md:w-44" value={status} onChange={(e)=>setStatus(e.target.value)}><option>Semua</option>{[...new Set(documents.map((item)=>item.status))].map((item)=><option key={item}>{item}</option>)}</select></FilterBar>
    {filtered.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((doc)=><article key={doc.id} className="premium-card border border-border bg-white p-5 shadow-soft"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-100 text-brand-700"><FileText size={19}/></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{doc.status}</span></div><h3 className="mt-4 font-bold text-ink">{doc.title}</h3><div className="mt-2 text-xs leading-5 text-muted">{doc.id}<br/>{doc.batchId}<br/>{formatDateTime(doc.createdAt)}</div><div className="mt-5 grid grid-cols-3 gap-2"><button className="btn-secondary !px-2 !py-2 text-xs" onClick={()=>setSelected(doc)}>Lihat</button><button className="btn-secondary !px-2 !py-2 text-xs" onClick={()=>window.print()}>Cetak</button><button className="btn-primary !px-2 !py-2 text-xs" onClick={()=>download(doc)}>Unduh</button></div></article>)}</div>:<div className="grid min-h-60 place-items-center border border-dashed border-border bg-white p-8 text-center"><div><FileText className="mx-auto text-brand-600"/><h3 className="mt-3 font-bold text-ink">Belum ada dokumen yang sesuai</h3><p className="mt-2 max-w-md text-sm text-muted">Ubah filter atau selesaikan tahapan batch agar dokumen terkait dapat diterbitkan.</p></div></div>}
    <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.title||'Pratinjau dokumen'}>{selected&&<div className="print-area"><div className="border border-border p-6"><div className="text-xs font-bold uppercase tracking-[.16em] text-brand-700">JELANTARA</div><h3 className="mt-2 text-xl font-bold text-ink">{selected.title}</h3><DetailList items={[["Document ID",selected.id],["Batch ID",selected.batchId],["Jenis",selected.type],["Status",selected.status],["Versi",selected.version],["Pihak terkait",selected.parties],["Tanggal",formatDateTime(selected.createdAt)]]}/><p className="mt-6 border-t border-border pt-4 text-xs leading-5 text-muted">Dokumen ini merupakan keluaran simulasi front-end dan bukan dokumen operasional atau sertifikasi resmi.</p></div></div>}</Modal>
  </>
}
